version: "3.8"

services:
  banco:
    image: bitnami/postgresql:13
    container_name: oraculo-banco-registros
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      DATABASE_HOST: ${DB_HOST}
    ports:
      - "5431:${DB_PORT}"
    networks:
      - registros-network
    volumes:
      - postgresdb:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: oraculo-pgadmin-registros
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - banco
    links:
      - banco:${DB_HOST}
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - registros-network

  registros:
    container_name: oraculo-registros
    build: .
    restart: always
    depends_on:
      - banco
    networks:
      - registros-network
    links:
      - banco:${DB_HOST}
    ports:
      - "${APP_PORT}:${APP_PORT}"

volumes:
  node_modules:
  postgresdb:

networks:
  registros-network:
    name: registros-network
    driver: bridge
